// Used for displaying 3rd party libraries info

const package = {
  "name": "stampede-cpanel-ui",
  "version": "1.0.0",
  "homepage": ".",
  "private": true,
  "dependencies": {
    "@babel/eslint-parser": "7.15.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.14.5",
    "@babel/plugin-proposal-optional-chaining": "7.14.5",
    "@babel/runtime": "7.15.3",
    "@emotion/react": "^11.8.1",
    "@emotion/styled": "^11.8.1",
    "@microsoft/signalr": "^6.0.1",
    "@mui/icons-material": "^5.4.4",
    "@mui/material": "^5.4.4",
    "@types/lodash": "4.14.175",
    "@types/react": "17.0.20",
    "@types/react-dom": "17.0.9",
    "@types/react-redux": "7.1.18",
    "@types/react-router": "5.1.16",
    "axios": "^0.19.0",
    "babel-jest": "^26.6.0",
    "chart.js": "^3.7.1",
    "connected-react-router": "6.5.2",
    "eslint-config-airbnb": "18.2.1",
    "eslint-plugin-jest-dom": "3.9.0",
    "fmlx-common-ui": "0.1.10",
    "history": "4.10.1",
    "immutable": "4.0.0-rc.14",
    "inversify": "^6.0.1",
    "inversify-react": "^1.0.1",
    "jest-config": "27.2.0",
    "jquery": "3.5.1",
    "lodash": "4.17.21",
    "merge": "2.1.1",
    "moment": "2.29.1",
    "msw": "0.35.0",
    "popper.js": "1.16.0",
    "prop-types": "15.7.2",
    "qs": "6.10.1",
    "react": "17.0.2",
    "react-chartjs-2": "^4.0.1",
    "react-dom": "17.0.2",
    "react-redux": "7.1.1",
    "react-router": "^6.2.1",
    "react-router-dom": "^6.2.1",
    "react-scripts": "4.0.3",
    "react-selectable": "2.1.1",
    "reactstrap": "8.1.1",
    "redux": "4.0.4",
    "redux-devtools-extension": "2.13.9",
    "redux-thunk": "2.3.0",
    "reflect-metadata": "^0.1.13",
    "sass": "^1.43.4",
    "svgo": "1.3.0",
    "typescript": "4.3.5"
  },
  "devDependencies": {
    "@babel/cli": "7.10.5",
    "@babel/core": "7.10.5",
    "@babel/plugin-proposal-class-properties": "7.10.4",
    "@babel/preset-env": "7.10.4",
    "@babel/preset-react": "7.10.4",
    "@storybook/linter-config": "3.1.2",
    "@testing-library/jest-dom": "5.14.1",
    "@testing-library/react": "12.0.0",
    "@testing-library/user-event": "13.2.1",
    "@types/history": "4.7.3",
    "@types/jest": "^26.0.24",
    "@types/node": "12.11.6",
    "@types/reactstrap": "8.0.6",
    "@typescript-eslint/eslint-plugin": "4.29.3",
    "@typescript-eslint/parser": "4.29.3",
    "cross-env": "6.0.3",
    "eslint": "7.32.0",
    "eslint-config-airbnb-typescript": "13.0.1",
    "eslint-plugin-flowtype": "3.13.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "24.4.0",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.21.5",
    "eslint-plugin-react-hooks": "1.7.0",
    "eslint-plugin-testing-library": "4.12.0",
    "nan": "2.14.1",
    "ts-jest": "^26.5.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "watch": "tsc --watch -p tsconfig.json",
    "build": "react-scripts build",
    "test": "jest --silent",
    "test:coverage": "jest --silent --coverage",
    "eject": "react-scripts eject",
    "lint": "eslint ./src/**/*.ts ./src/**/*.tsx"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
